# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "honey & thread"
description: > # this means to ignore newlines until "email:"
  

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Honey & Thread'
author: 'Mandy Gross '
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://mandygross.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/honeyandthread
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	instagram
    url:	https://instagram.com/mandy.gross
    desc: Follow me on Instagram
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	Pinterest
    url:	https://www.pinterest.com/honeyandthread/
    desc:	Pin with me on Pinterest
#    share_url: 
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
